describe("Theme System Integration", function()
  local theme_module
  local engine_module

  before_each(function()
    theme_module = require("cumulus.theme")
    engine_module = require("cumulus.util.engine")
  end)

  describe("Theme switching", function()
    it("should set AWS theme when requested", function()
      theme_module.set_theme("aws")
      local current = theme_module.get_current_theme()
      assert.are.equal("aws-theme", current)
    end)

    it("should set Azure theme when requested", function()
      theme_module.set_theme("azure")
      local current = theme_module.get_current_theme()
      assert.are.equal("azure-theme", current)
    end)

    it("should set GCP theme when requested", function()
      theme_module.set_theme("gcp")
      local current = theme_module.get_current_theme()
      assert.are.equal("gcp-theme", current)
    end)

    it("should set OCI theme when requested", function()
      theme_module.set_theme("oci")
      local current = theme_module.get_current_theme()
      assert.are.equal("oci-theme", current)
    end)

    it("should handle theme names with -theme suffix", function()
      theme_module.set_theme("aws-theme")
      local current = theme_module.get_current_theme()
      assert.are.equal("aws-theme", current)
    end)
  end)

  describe("Error handling", function()
    it("should reject empty theme name", function()
      local ok = pcall(theme_module.set_theme, "")
      assert.is_false(ok)
    end)

    it("should reject nil theme name", function()
      local ok = pcall(theme_module.set_theme, nil)
      assert.is_false(ok)
    end)

    it("should reject invalid provider name", function()
      local ok = pcall(theme_module.set_theme, "invalid-provider")
      assert.is_false(ok)
    end)
  end)

  describe("Theme initialization", function()
    it("should load saved theme on setup", function()
      theme_module.setup({ theme = "azure-theme" })
      local current = theme_module.get_current_theme()
      assert.are.equal("azure-theme", current)
    end)

    it("should use default theme when none specified", function()
      theme_module.setup()
      local current = theme_module.get_current_theme()
      assert.is_not_nil(current)
      assert.is.truthy(current:match("^%w+%-theme$"))
    end)
  end)

  describe("Theme utilities", function()
    it("should return valid current theme format", function()
      local current = theme_module.get_current_theme()
      assert.is_not_nil(current)
      assert.are.equal(current, current:gsub("%-theme$", "") .. "-theme")
    end)
  end)
end)
